export const states = {
  baseline: {
    label: "Mốc sạch",
    collection: "papers-baseline",
    paperCount: 24,
    hitRate: 91.7,
    accuracy: 83.3,
    tokenF1: 0.78,
    judgeScore: 4.4,
    qualityPassed: 8,
    qualityTotal: 8,
    freshRecords: 22,
    trustScore: 94,
    trustLabel: "Ngữ cảnh tốt",
    hitDelta: "Mốc tham chiếu ban đầu",
    qualityLabel: "Tất cả kiểm tra đều đạt",
    freshLabel: "2 bản ghi vượt ngưỡng tuổi",
  },
  corrupted: {
    label: "Cố ý làm lỗi",
    collection: "papers-corrupted",
    paperCount: 21,
    hitRate: 58.3,
    accuracy: 50.0,
    tokenF1: 0.46,
    judgeScore: 2.8,
    qualityPassed: 3,
    qualityTotal: 8,
    freshRecords: 13,
    trustScore: 48,
    trustLabel: "Ngữ cảnh suy giảm",
    hitDelta: "Giảm 33,4 điểm so với ban đầu",
    qualityLabel: "5 kiểm tra cần xử lý",
    freshLabel: "8 bản ghi vượt ngưỡng tuổi",
  },
  repaired: {
    label: "Sau phục hồi",
    collection: "papers-repaired",
    paperCount: 24,
    hitRate: 91.7,
    accuracy: 83.3,
    tokenF1: 0.78,
    judgeScore: 4.4,
    qualityPassed: 8,
    qualityTotal: 8,
    freshRecords: 22,
    trustScore: 94,
    trustLabel: "Ngữ cảnh đã phục hồi",
    hitDelta: "Đã phục hồi 33,4 điểm",
    qualityLabel: "Tất cả kiểm tra đã phục hồi",
    freshLabel: "2 bản ghi vượt ngưỡng tuổi",
  },
};

export const papers = [
  {
    id: "10.1145/agentic-rag.2026.014",
    title: "Hệ thống truy xuất có tác tử cho mô hình ngôn ngữ dựa trên bằng chứng",
    authors: "M. Chen, A. Rivera, S. Patel",
    published: "28 thg 7, 2026",
    category: "Truy xuất",
    score: 0.94,
    status: "healthy",
    summary: "Khung lập kế hoạch truy vấn lặp, truy xuất và xác minh bằng chứng trong hệ thống RAG có tác tử.",
  },
  {
    id: "10.48550/arXiv.2607.11842",
    title: "RAG thích ứng: Học khi nào và cần truy xuất điều gì",
    authors: "J. Park, N. Singh",
    published: "21 thg 7, 2026",
    category: "Mô hình ngôn ngữ lớn",
    score: 0.89,
    status: "healthy",
    summary: "Chính sách truy xuất thích ứng giảm ngữ cảnh không cần thiết và tăng độ bám nguồn cho câu hỏi phức tạp.",
  },
  {
    id: "10.1016/j.ipm.2026.104201",
    title: "Đánh giá RAG trong điều kiện dữ liệu dịch chuyển",
    authors: "L. Nguyen, R. Garcia",
    published: "09 thg 6, 2026",
    category: "Đánh giá",
    score: 0.86,
    status: "healthy",
    summary: "Đánh giá có kiểm soát chất lượng truy xuất và câu trả lời khi kho tài liệu thiếu hụt hoặc lỗi thời.",
  },
  {
    id: "10.1109/TKDE.2026.3369102",
    title: "Tín hiệu chất lượng dữ liệu cho pipeline RAG thực tế",
    authors: "E. Wilson, H. Ito",
    published: "16 thg 5, 2026",
    category: "Giám sát dữ liệu",
    score: 0.82,
    status: "stale",
    summary: "Kết nối kiểm tra chất lượng cấp bản ghi và chỉ số độ mới với hiệu năng truy xuất phía sau.",
  },
  {
    id: "10.1145/repair-rag.2026.008",
    title: "Pipeline dữ liệu có thể phục hồi cho trợ lý AI đáng tin cậy",
    authors: "S. Hassan, D. Moore",
    published: "30 thg 4, 2026",
    category: "Kỹ thuật dữ liệu",
    score: 0.79,
    status: "healthy",
    summary: "Mẫu phục hồi dựa trên snapshot giúp đánh giá AI có thể tái lập và sửa pipeline có thể kiểm toán.",
  },
];

export const evaluations = [
  { id: "Q-01", type: "Tóm tắt", question: "Điều gì định nghĩa RAG có tác tử?", hit: true, score: 5 },
  { id: "Q-02", type: "So sánh", question: "So sánh các chính sách truy xuất thích ứng", hit: true, score: 4 },
  { id: "Q-03", type: "Độ mới", question: "Những bài báo nào mới nhất?", hit: true, score: 5 },
  { id: "Q-04", type: "Tra cứu", question: "Tìm bài báo theo DOI 10.1109…", hit: true, score: 4 },
  { id: "Q-05", type: "Tổng hợp", question: "Dữ liệu dịch chuyển ảnh hưởng đến RAG thế nào?", hit: false, score: 3 },
];

export const comparisonMetrics = [
  { label: "Truy xuất đúng", baseline: 91.7, corrupted: 58.3, repaired: 91.7, suffix: "%" },
  { label: "Độ chính xác đánh giá", baseline: 83.3, corrupted: 50.0, repaired: 83.3, suffix: "%" },
  { label: "Token F1", baseline: 78, corrupted: 46, repaired: 78, suffix: "" },
];

export const mockAnswer = {
  text: "Kho tài liệu mô tả nhất quán RAG có tác tử là một quá trình truy xuất dựa trên phản hồi. Thay vì chỉ truy xuất một lần, tác tử lập kế hoạch tìm kiếm, đánh giá bằng chứng trả về, viết lại truy vấn khi bằng chứng còn yếu và chỉ sau đó mới tạo câu trả lời có căn cứ. Các nguồn mạnh nhất cũng nhấn mạnh tính truy xuất nguồn gốc: mọi nhận định phải có thể lần ngược về mã tài liệu.",
  sourceIds: [0, 1],
};
